title: Learn Code Repeat
description: Day of learning about stuff.

url: http://learncoderepeat.org
baseurl: "http://learncoderepeat.org"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Speakers
   url: /speakers
 - title: Event Details
   url: /eventdetails

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: ""
